### ISSUE TITLE
Loading the pg_array extension

### ISSUE THREAD

**Issue by tombenner** [mattt/rack-push-notification#14]
While using Helios, I ran into mattt/sinatra-param#28 and noticed that an Issue hadn't been created for it here yet, so I'm creating it :).

Adding `Sequel::Model.db.extension :pg_array` before [`create_table :push_notification_devices`](https://github.com/mattt/rack-push-notification/blob/master/lib/rack/push-notification/migrations/001_base_schema.rb#L3) resolves it for me. Is that a reasonable solution? I'm happy to open a PR if so, but obviously feel free to add a fix directly, if that's easier. Thanks!

**Comment by tombenner** [comment]
Actually, this wouldn't belong in a migration, but rather next to the existing [Sequel.extension call](https://github.com/mattt/rack-push-notification/blob/master/lib/rack/push-notification.rb#L20). Unlike the other extensions there, the pg_array extension apparently needs to be loaded into the Sequel::Postgres::Database instance. The issue is resolved for me when I replace:

```ruby
Sequel.extension :pg_inet, :pg_array, :migration`
```
with:

```ruby
Sequel.extension :pg_inet, :migration
Sequel::Model.db.extension :pg_array
```

**Comment by mattt** [comment]
That second approach sounds like the correct fix. Yes, please send a PR with this change.
